### ISSUE TITLE
Skein: Zoom please? Pan is very slow as well. Clear FULL skein in one click?

### ISSUE THREAD

**Issue by artao5** [DavidKinder/Windows-Inform7#1]
Just a couple requests here, as per the thread title.
When the skein gets big, it would be REALLY useful to be able to zoom in and out to navigate quickly.
Regarding that, the middle-click panning function is VERY slow and not smooth.
Finally, being able to clear the ENTIRE skein with one click would be very very nice, as the skein gets QUITE full rather quickly as one is building a game. Having to delete every thread individually is very tiresome.
Similarly, it would be very nice if one could select multiple threads to delete in one go, rather than the entire skein (tho both, of course, would be very useful)
Also wondering when an official build will be available for download next. I'm not really "up to" compiling from source.
Thanks for your work! :D

**Comment by DavidKinder** [comment]
The last update to the Windows build was in March this year: you can get that latest build from http://inform7.com/ or http://ifarchive.org/indexes/if-archiveXinfocomXcompilersXinform7Xexecutables.html

In recent Windows builds there has been some work to catch up with the skein as it is in the OSX front end. On the right-click menu for skein nodes there is "Delete Threads From Here" and also "Trim", which removes all unlocked nodes below.

I don't know quite when the next build will be: the only recent changes have been overhauling the preferences dialog, which isn't quite finished yet.

In general, bug reports are best at http://inform7.com/mantis/view_all_bug_page.php, and new feature requests at https://inform7.uservoice.com/forums/57320-general/. There's still quite a lot of work to do for the Windows front-end to catch up with OSX, so that will most likely be the immediate priority.

Thanks for the suggestions!

**Comment by DavidKinder** [comment]
I'm closing this issue as the middle-click panning in the skein should be fixed in the latest source. The remaining comments in this issue are really feature requests, which are more suited to being reported at the Inform7 UserVoice page, as noted in the previous comment.
