### ISSUE TITLE
Button which pastes code examples from extension documentation does not work

### ISSUE THREAD

**Issue by sideburns3000** [DavidKinder/Windows-Inform7#29]
The button which pastes code examples from extension documentation into the Source panel does not seem to work (using the latest release, beta 4, on Windows 8.1 -- but the issue happened already with a previous version; I didn't get around to reporting it earlier).
 
The same goes for the button at the top beside the extension title, which should paste the line `'Include <ext. title> by <ext. author>.'` into the Source panel. 

In contrast to that, the button to copy examples from the normal included documentation (WWI/RB) does work.

Steps to reproduce:
1. Open an extension in the Extensions panel.
2. Click on the small "copy/paste" button next to the extension's title, or on the button next to a code example's title. 

Selecting and copy-pasting the code examples by hand is a workaround, but unfortunately, not a very good one, because the formatting is not preserved completely -- for example, paragraph breaks are missing, which causes the compiler to misunderstand the code.

I know that the Gnome-Inform7 IDE is a separate project, but for what it's worth, the same issue seems to have cropped up there and was fixed in the gtk3 branch by this commit:

https://github.com/ptomato/gnome-inform7/commit/9858f7629ca6431694b5cb22406ce14769b90f90
("panel: Allow loading internal JS in Extensions pages")

Thanks for your work on the IDE!

Regards,
Michael

**Comment by DavidKinder** [comment]
Fixed by commit 19040d2c0b143b1eedf1b00e54cb04efa39af192.

This turns out to be a different issue to that seen in the Gnome front-end: the HTML generated by the Inform 7 compiler usually has a Javascript function project() that returns the "project" object which allows the Javascript to call back into the front-end. But the generated extension documentation sometimes lacks this, so the front-end now provides its own fall-back implementation.

**Comment by sideburns3000** [comment]
That's great, thanks!
