### ISSUE TITLE
Gluxle interpreter being flagged as infected by antivirus

### ISSUE THREAD

**Issue by Godel23** [DavidKinder/Windows-Inform7#64]
(not sure if this is the right place to flag this - but just to let you know that when I try to extract the gluxle interpretor my antivirus (bitdefender) flags it as infected with a virus. I assume it's probably a false flag, but it's preventing the interpretor in the IDE from running because of the missing file

**Comment by DavidKinder** [comment]
Yes, there have been several instances of this happening recently with various anti-virus tools. I've rebuilt the interpreter from scratch on several machines to double check, and it's definitely not infected. There's nothing else I can really do about it - you can see if your AV vendor allows subsmissions for false positives, some do, and see if you can selectively disable scanning for directories in order to get the front-end to be able to work.

**Comment by Godel23** [comment]
Thanks for getting back to me.

I've submitted the false positive report, which will hopefully chip away at
the problem!

Regards,
Matthew

**Comment by DavidKinder** [comment]
I recently also entered and implemented https://github.com/DavidKinder/Windows-Inform7/issues/63, so at least if this happens the user gets a message giving them a clue where to look, rather than just a blank Story tab.
